### ISSUE TITLE
broken CUDA build?

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#176]
This build is failing:

http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=IKTRideTrilinosCUDA

What is strange about it is that the Trilinos source repository being used is currently in a detached head state, pointing to a very old commit.

@ikalash do you know more about this build?

**Comment by ikalash** [comment]
@ibaned .  This is my CUDA build on Ride.  I noticed too that it failed last night it looks like due to changes in Trilinos.

**Comment by ibaned** [comment]
unless I misinterpreted the way this build is setup, its compiling a version of Trilinos from 2015?

**Comment by ikalash** [comment]
No, a new Trilinos and Albany are pulled and built each night.  I think the first commit happens to be from 2015 for some reason, but all the others are current.  If I do git log, I see:

commit c59963d0319c2c8cdd27a531b5293c44e44fe25a
Author: Andrey Prokopenko <aprokop@sandia.gov>
Date:   Thu Sep 17 13:03:45 2015 -0600

    Teuchos: use provided stream formatting flags in TimeMonitor summarize()
    
    This allows the user to control the formatting of the timer columns.
    The cost is storing an extra std::ios_base::fmtflags in TableEntry.
    
    Build/Test Cases Summary
    Enabled Packages: TeuchosComm
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=2322,notpassed=0 (661.75 min)

commit 611e3ebb75ecdb4228ab5f3f5e0f844b412cea84
Merge: 91208e4 da54b1e
Author: Mark Hoemmen <mhoemme@sandia.gov>
Date:   Thu Aug 31 16:21:46 2017 -0600

**Comment by ibaned** [comment]
I did `git status` in that directory and saw it stuck at "detached HEAD". I don't think a repository in a detached HEAD state will update properly.

**Comment by ibaned** [comment]
but the 2017 one is interesting..

**Comment by aprokop** [comment]
> I think the first commit happens to be from 2015 for some reason, but all the others are current.

Yes, this is a recently merged commit. I have finally decided to merge an outstanding patch.

**Comment by ikalash** [comment]
The clone of Trilinos and Albany on ride is done by Jenkins; then those builds are copied into the /home/projects/albany/repos directories.  Could this be why it says detached head?  I am sure the branches are develop and master for Trilinos and Albany respectively and that they are cloned from scratch each night.

**Comment by ibaned** [comment]
Ah okay, that plus @aprokop 's clarification should explain the weirdness. So I guess something recent did break CUDA.

**Comment by ikalash** [comment]
I think so.  Maybe worth opening a Trilinos github issue?

**Comment by ibaned** [comment]
I think its Tpetra packing stuff (recent changes to this have caused lots of issues):
```
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1088): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &) [with DataType=const Sacado::MP::Vector<Tpetra::SFS_int_double_16_DFN
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(474): here
            instantiation of "Kokkos::pair<int, size_t> Tpetra::Details::packCrsMatrixRow<ST,ColumnMap,BufferDeviceType>(const ColumnMap &, const Kokkos::View<char *, BufferDev
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(621): here
            instantiation of "void Tpetra::Details::PackCrsMatrixFunctor<LocalMatrix, LocalMap, BufferDeviceType>::operator()(Tpetra::Details::PackCrsMatrixFunctor<LocalMatrix,
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(687): here
            instantiation of "std::enable_if<std::is_same<TagType, void>::value, void>::type Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerTy
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(719): here
            instantiation of "void Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerType, Kokkos::Cuda>::run(const Kokkos::Impl::ParallelReduce<
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(697): here
            [ 4 instantiation contexts not shown ]
            instantiation of "void Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(const std::__cxx11::string &, const PolicyType &, const Fun
/home/projects/albany/repos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel_Reduce.hpp(1213): here
            instantiation of "void Kokkos::parallel_reduce(const PolicyType &, const FunctorType &, ReturnType &, Kokkos::Impl::enable_if<Kokkos::is_execution_policy<PolicyType
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(702): here
            instantiation of "void Tpetra::Details::do_pack(const LocalMatrix &, const LocalMap &, const Kokkos::View<char *, BufferDeviceType> &, const Tpetra::Details::PackTr
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(901): here
            instantiation of "void Tpetra::Details::packCrsMatrixImpl(const Tpetra::CrsMatrix<ST, LO, GO, NT, NT::classic> &, Kokkos::DualView<char *, BufferDeviceType, void, v
/home/projects/albany/repos/Trilinos/packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp(965): here
            instantiation of "void Tpetra::Details::packCrsMatrix(const Tpetra::CrsMatrix<ST, LO, GO, NT, false> &, Teuchos::Array<char> &, const Teuchos::ArrayView<size_t> &,
/home/projects/albany/build/TriBuild/packages/stokhos/src/Tpetra_Details_packCrsMatrix_MP_Vector_Cuda.cpp(54): here
```
I think I'll just open a Trilinos issue.

**Comment by ikalash** [comment]
Sounds good to me, thanks for doing that.  Hopefully the Tpetra folks will resolve it soon.

**Comment by mhoemmen** [comment]
btw what version of CUDA is this?  I've been testing all the way through Stokhos (takes forever) with CUDA 8.0.  Does this use 7.5?

**Comment by ibaned** [comment]
pretty sure its 8.0, namely `openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44`

**Comment by ibaned** [comment]
Also, the Kokkos `static_assert` isn't affected by CUDA version

**Comment by ibaned** [comment]
The log file is 300MB due to warnings, so it took me a little more time, but I extracted the configuration:
```
"/home/projects/pwr8-rhel73-lsf/cmake/3.6.2/bin/cmake" 
"-DCMAKE_INSTALL_PREFIX:PATH=/home/projects/albany//build/TrilinosInstall" 
"-DCMAKE_BUILD_TYPE:STRING=RELEASE" 
"-DCMAKE_CXX_COMPILER:FILEPATH=/home/projects/albany//nvcc_wrapper_p100" 
"-DCMAKE_CXX_FLAGS:STRING=-fopenmp 
-mcpu=power8 
-lgfortran 
-arch=sm_60" 
"-DCMAKE_C_FLAGS:STRING=-fopenmp 
-mcpu=power8 
-lgfortran" 
"-DCMAKE_Fortran_FLAGS:STRING=-lgfortran 
-fopenmp 
-mcpu=power8" 
"-DCMAKE_EXE_LINKER_FLAGS=-fopenmp 
-mcpu=power8 
-ldl 
-lgfortran" 
"-DTrilinos_EXTRA_LINK_FLAGS:STRING=-fopenmp 
-mcpu=power8 
-ldl 
-lgfortran" 
"-DCMAKE_SKIP_RULE_DEPENDENCY=ON" 
"-DTPL_ENABLE_MPI:BOOL=ON" 
"-DTPL_ENABLE_MPI:BOOL=ON" 
"-DMPI_EXEC=mpirun" 
"-DMPI_EXEC_NUMPROCS_FLAG:STRING=-n" 
"-DTPL_ENABLE_BLAS:BOOL=ON" 
"-DBLAS_LIBRARY_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/openblas/0.2.19/gcc/5.3.0/lib" 
"-DBLAS_LIBRARY_NAMES:STRING=blas" 
"-DTPL_ENABLE_LAPACK:BOOL=ON" 
"-DLAPACK_LIBRARY_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/openblas/0.2.19/gcc/5.3.0/lib" 
"-DLAPACK_LIBRARY_NAMES:STRING=lapack" 
"-DTPL_ENABLE_Boost:BOOL=ON" 
"-DBoost_INCLUDE_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/boost/1.60.0/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include" 
"-DTPL_ENABLE_BoostLib:BOOL=ON" 
"-DBoostLib_INCLUDE_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/boost/1.60.0/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include" 
"-DBoostLib_LIBRARY_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/boost/1.60.0/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/lib" 
"-DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF" 
"-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF" 
"-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF" 
"-DTrilinos_ENABLE_CXX11:BOOL=ON" 
"-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF" 
"-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON" 
"-DTrilinos_VERBOSE_CONFIGURE:BOOL=OFF" 
"-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=" 
"-DHAVE_INTREPID_KOKKOSCORE:BOOL=ON" 
"-DKokkos_ENABLE_CXX11:BOOL=ON" 
"-DKokkos_ENABLE_Cuda_UVM:BOOL=ON" 
"-DKokkos_ENABLE_EXAMPLES:BOOL=OFF" 
"-DKokkos_ENABLE_OpenMP:BOOL=OFF" 
"-DKokkos_ENABLE_Pthread:BOOL=OFF" 
"-DKokkos_ENABLE_Serial:BOOL=ON" 
"-DKokkos_ENABLE_TESTS:BOOL=ON" 
"-DTPL_ENABLE_Thrust:BOOL=ON" 
"-DTPL_ENABLE_CUDA:BOOL=ON" 
"-DTPL_ENABLE_CUSPARSE:BOOL=ON" 
"-DAmesos2_ENABLE_KLU2:BOOL=ON" 
"-DEpetraExt_USING_HDF5:BOOL=OFF" 
"-DIntrepid_ENABLE_TESTS:BOOL=OFF" 
"-DIntrepid2_ENABLE_TESTS:BOOL=OFF" 
"-DPhalanx_INDEX_SIZE_TYPE:STRING=UINT" 
"-DPhalanx_KOKKOS_DEVICE_TYPE:STRING=CUDA" 
"-DSacado_ENABLE_COMPLEX:BOOL=ON" 
"-DTeuchos_ENABLE_COMPLEX:BOOL=ON" 
"-DTpetra_ENABLE_Kokkos_Refactor:BOOL=ON" 
"-DTPL_ENABLE_Matio:BOOL=OFF" 
"-DTPL_ENABLE_Netcdf:BOOL=ON" 
"-DTPL_Netcdf_INCLUDE_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/netcdf/4.4.1/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include" 
"-DTPL_Netcdf_LIBRARIES=/home/projects/pwr8-rhel73-lsf/netcdf/4.4.1/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/lib/libnetcdf.a" 
"-DTPL_Netcdf_PARALLEL:BOOL=ON" 
"-DTPL_ENABLE_Pnetcdf:STRING=ON" 
"-DTPL_Pnetcdf_INCLUDE_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/pnetcdf/1.6.1/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include" 
"-DTPL_Pnetcdf_LIBRARIES=/home/projects/pwr8-rhel73-lsf/pnetcdf/1.6.1/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/lib/libpnetcdf.a" 
"-DTPL_ENABLE_HDF5:STRING=ON" 
"-DTPL_HDF5_INCLUDE_DIRS:PATH=/home/projects/pwr8-rhel73-lsf/hdf5/1.8.17/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/include" 
"-DTPL_HDF5_LIBRARIES=/home/projects/pwr8-rhel73-lsf/hdf5/1.8.17/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/lib/libhdf5_hl.a" 
"-DTrilinos_EXTRA_LINK_FLAGS:STRING='-lnetcdf 
-lpnetcdf 
-lhdf5_hl 
-lhdf5 
-lz'" 
"-DTPL_ENABLE_X11:BOOL=OFF" 
"-DTrilinos_ENABLE_Amesos2:BOOL=ON" 
"-DTrilinos_ENABLE_Amesos:BOOL=ON" 
"-DTrilinos_ENABLE_Anasazi:BOOL=ON" 
"-DTrilinos_ENABLE_AztecOO:BOOL=ON" 
"-DTrilinos_ENABLE_Belos:BOOL=ON" 
"-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF" 
"-DTrilinos_ENABLE_Epetra:BOOL=ON" 
"-DTrilinos_ENABLE_EpetraExt:BOOL=ON" 
"-DTrilinos_ENABLE_Ifpack2:BOOL=ON" 
"-DTrilinos_ENABLE_Ifpack:BOOL=ON" 
"-DTrilinos_ENABLE_Intrepid:BOOL=ON" 
"-DTrilinos_ENABLE_Intrepid2:BOOL=ON" 
"-DTrilinos_ENABLE_Kokkos:BOOL=ON" 
"-DTrilinos_ENABLE_KokkosAlgorithms:BOOL=ON" 
"-DTrilinos_ENABLE_KokkosContainers:BOOL=ON" 
"-DTrilinos_ENABLE_KokkosCore:BOOL=ON" 
"-DTrilinos_ENABLE_KokkosExample:BOOL=OFF" 
"-DTrilinos_ENABLE_ML:BOOL=ON" 
"-DTrilinos_ENABLE_OpenMP:BOOL=OFF" 
"-DTrilinos_ENABLE_MiniTensor:BOOL=ON" 
"-DTrilinos_ENABLE_MueLu:BOOL=ON" 
"-DTrilinos_ENABLE_NOX:BOOL=ON" 
"-DTrilinos_ENABLE_Pamgen:BOOL=ON" 
"-DTrilinos_ENABLE_Phalanx:BOOL=ON" 
"-DTrilinos_ENABLE_Piro:BOOL=ON" 
"-DTrilinos_ENABLE_Rythmos:BOOL=ON" 
"-DTrilinos_ENABLE_SEACAS:BOOL=ON" 
"-DTrilinos_ENABLE_SEACASAprepro_lib:BOOL=ON" 
"-DTrilinos_ENABLE_STKClassic:BOOL=OFF" 
"-DTrilinos_ENABLE_STKDoc_tests:BOOL=OFF" 
"-DTrilinos_ENABLE_STKIO:BOOL=ON" 
"-DTrilinos_ENABLE_STKMesh:BOOL=ON" 
"-DTrilinos_ENABLE_Sacado:BOOL=ON" 
"-DTrilinos_ENABLE_Shards:BOOL=ON" 
"-DTrilinos_ENABLE_Stokhos:BOOL=ON" 
"-DTrilinos_ENABLE_Stratimikos:BOOL=ON" 
"-DTrilinos_ENABLE_TESTS:BOOL=OFF" 
"-DTrilinos_ENABLE_Teko:BOOL=ON" 
"-DTrilinos_ENABLE_Teuchos:BOOL=ON" 
"-DTrilinos_ENABLE_ThreadPool:BOOL=ON" 
"-DTrilinos_ENABLE_Thyra:BOOL=ON" 
"-DTrilinos_ENABLE_Tpetra:BOOL=ON" 
"-DTrilinos_ENABLE_Zoltan2:BOOL=ON" 
"-DTrilinos_ENABLE_Zoltan:BOOL=ON" 
"-DIntrepid2_ENABLE_KokkosDynRankView:BOOL=ON" 
"-GUnix 
Makefiles" 
"/home/projects/albany/repos/Trilinos"
```

**Comment by mhoemmen** [comment]
Weird -- I tested with GCC 5.4.0 + CUDA 8.0.44, as well as Clang 3.9.  The check-in test script tests with GCC (no CUDA).

**Comment by mhoemmen** [comment]
"recent changes to this have caused lots of issues" -- it also sped up Aria load complete quite a bit ;-)  we'll work it out -- I just want to reassure you that we do actually test with CUDA.

**Comment by ibaned** [comment]
> it also sped up Aria load complete quite a bit ;-) 

Awesome. Yea, I just grumble about obscure compiles, but I know the code is being modified for good reasons and tested as much as is reasonable.

**Comment by mhoemmen** [comment]
Trilinos still needs better CUDA test coverage, though :-) .

**Comment by tjfulle** [comment]
Thanks for the configuration @ibaned!  I've been testing quite a bit on CUDA, but probably not that far downstream of Tpetra.  I'll see about reproducing the error with your configuration and go from there.

**Comment by tjfulle** [comment]
@ibaned and @ikalash, with the configuration attached (based on the configuration that @ibaned posted), Trilinos builds without error (on `ride.sandia.gov`) with my latest branch (see PR [1665](https://github.com/trilinos/Trilinos/pull/1665)).  I am building with the `develop` branch of Trilinos as we speak.  I'll post the results as I get them.

[do-configure-ride.txt](https://github.com/gahansen/Albany/files/1273208/do-configure-ride.txt)

**Comment by ibaned** [comment]
Thanks @tjfulle !

**Comment by mhoemmen** [comment]
Hm, my CUDA 7.5 doesn't build with Boost 1.59 (the default SEMS Boost):
```
/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.8.4/base/include/boost/geometry/algorithms/detail/relate/result.hpp(609): error: "boost::geometry::detail::relate::mask_handler<Mask, Interrupt>::mask_handler()" provides no initializer for:
            reference member "boost::geometry::detail::relate::mask_handler<Mask, Interrupt>::m_mask"

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.8.4/base/include/boost/serialization/array.hpp(57): warning: missing return statement at end of non-void function "boost::serialization::array<T>::operator="
```

**Comment by tjfulle** [comment]
With the develop branch and the attached configure script, I get a clean build.  @ibaned or @ikalash could one of you send me the actual configure script that results in failure?

[do-configure-ride-develop.txt](https://github.com/gahansen/Albany/files/1273309/do-configure-ride-develop.txt)

**Comment by mhoemmen** [comment]
btw I've been getting this kokkos-kernels issue with my CUDA 7.5, GCC 4.8.4 build:

https://github.com/kokkos/kokkos-kernels/issues/72

The code looks harmless to me.

**Comment by tjfulle** [comment]
Adding to my last comment that the clean build is from the develop branch as of a few hours ago

**Comment by tjfulle** [comment]
@ibaned and/or @ikalash, never mind on the configuration request, I have been able to reproduce the build failure.  I had previously turned off building tests to cut down on build times (it is a build failure, so I figured I could diagnose it without building tests).  But, this code is not built if tests are disabled.

This is blocking some other work I am doing, so I hope to have it fixed soon :)

**Comment by ibaned** [comment]
This particular issue I think was fixed.
